import 'package:flutter/material.dart';
import '../../theme/app_theme.dart';

/// Help page with documentation and FAQs
class HelpPage extends StatelessWidget {
  const HelpPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Text(
            'Help & Documentation',
            style: Theme.of(context).textTheme.headlineMedium,
          ),
          const SizedBox(height: 4),
          Text(
            'Get help and learn how to use the clinical dashboard',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppTheme.textSecondary,
                ),
          ),
          const SizedBox(height: 24),

          // Quick links
          LayoutBuilder(
            builder: (context, constraints) {
              final crossAxisCount = constraints.maxWidth > 1000
                  ? 4
                  : constraints.maxWidth > 600
                      ? 2
                      : 1;
              return GridView.count(
                crossAxisCount: crossAxisCount,
                shrinkWrap: true,
                physics: const NeverScrollableScrollPhysics(),
                crossAxisSpacing: 16,
                mainAxisSpacing: 16,
                childAspectRatio: 1.5,
                children: const [
                  _HelpCard(
                    icon: Icons.menu_book_outlined,
                    iconColor: AppTheme.blue,
                    iconBgColor: AppTheme.blueLight,
                    title: 'Documentation',
                    subtitle: 'Read the full user guide',
                  ),
                  _HelpCard(
                    icon: Icons.play_circle_outline,
                    iconColor: AppTheme.purple,
                    iconBgColor: AppTheme.purpleLight,
                    title: 'Video Tutorials',
                    subtitle: 'Watch step-by-step guides',
                  ),
                  _HelpCard(
                    icon: Icons.chat_bubble_outline,
                    iconColor: AppTheme.green,
                    iconBgColor: AppTheme.greenLight,
                    title: 'Live Chat',
                    subtitle: 'Chat with support team',
                  ),
                  _HelpCard(
                    icon: Icons.email_outlined,
                    iconColor: AppTheme.amber,
                    iconBgColor: AppTheme.amberLight,
                    title: 'Email Support',
                    subtitle: 'support@clinic.com',
                  ),
                ],
              );
            },
          ),
          const SizedBox(height: 24),

          // FAQs
          Card(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Frequently Asked Questions',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                  const SizedBox(height: 16),
                  const _FaqItem(
                    question: 'How do I create a new patient encounter?',
                    answer:
                        'To create a new encounter, click on "New Encounter" in the sidebar. Select a patient from the dropdown, fill in the chief complaint and other clinical information, record vital signs, and add your assessment and plan. Click "Submit Encounter" when finished.',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'What are AI suggestions and how do they work?',
                    answer:
                        'AI suggestions are automated recommendations generated by analyzing your encounter data. They can help identify:\n• Missing vital signs\n• Red flags that require immediate attention\n• Values that should be rechecked\n• Documentation gaps\n\nYou can accept or ignore each suggestion, and all actions are logged for audit purposes.',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'How do I upload lab results or imaging?',
                    answer:
                        'Navigate to "File Uploads" in the sidebar. Select the patient, then either drag and drop files (PDF, JPG, PNG) into the upload area or click "Choose Files" to browse. You can also paste text results directly if you prefer.',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'Can I edit a patient summary after generating it?',
                    answer:
                        'Yes! After generating a patient summary, click the "Edit" button in the summary preview. You can modify any section including diagnosis, medications, home care instructions, and warning signs. Remember to save your changes before downloading or sending.',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'How do I set up reminders for patient follow-ups?',
                    answer:
                        'Go to "Reminders" in the sidebar and click "Add Reminder". Select the patient, choose the event type (follow-up, test, medication, or other), pick a date and time, and add any notes.',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'How do I search for specific encounters?',
                    answer:
                        'In the "All Encounters" section, use the search bar to find encounters by patient name or chief complaint. You can also filter by status (in-progress, pending-review, or finalized) using the dropdown menu.',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'What should I do if I encounter an error?',
                    answer:
                        'If you encounter an error:\n1. Try refreshing the page\n2. Check your internet connection\n3. Clear your browser cache\n4. Contact support if the issue persists\n\nEmail: support@clinic.com | Phone: (555) 123-4567',
                  ),
                  const Divider(),
                  const _FaqItem(
                    question: 'Is my patient data secure?',
                    answer:
                        'Yes. All data is encrypted in transit and at rest. We comply with HIPAA regulations and follow industry best practices for data security. Access is logged and audited.',
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 24),

          // Quick tips
          Card(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Quick Tips',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                  const SizedBox(height: 16),
                  LayoutBuilder(
                    builder: (context, constraints) {
                      if (constraints.maxWidth > 600) {
                        return Row(
                          children: const [
                            Expanded(
                              child: _QuickTip(
                                icon: Icons.help_outline,
                                iconColor: AppTheme.blue,
                                iconBgColor: AppTheme.blueLight,
                                title: 'Use keyboard shortcuts',
                                subtitle:
                                    'Press Ctrl+N to start a new encounter quickly',
                              ),
                            ),
                            SizedBox(width: 24),
                            Expanded(
                              child: _QuickTip(
                                icon: Icons.help_outline,
                                iconColor: AppTheme.purple,
                                iconBgColor: AppTheme.purpleLight,
                                title: 'Review suggestions regularly',
                                subtitle:
                                    'Check AI suggestions to improve documentation quality',
                              ),
                            ),
                          ],
                        );
                      }
                      return Column(
                        children: const [
                          _QuickTip(
                            icon: Icons.help_outline,
                            iconColor: AppTheme.blue,
                            iconBgColor: AppTheme.blueLight,
                            title: 'Use keyboard shortcuts',
                            subtitle:
                                'Press Ctrl+N to start a new encounter quickly',
                          ),
                          SizedBox(height: 16),
                          _QuickTip(
                            icon: Icons.help_outline,
                            iconColor: AppTheme.purple,
                            iconBgColor: AppTheme.purpleLight,
                            title: 'Review suggestions regularly',
                            subtitle:
                                'Check AI suggestions to improve documentation quality',
                          ),
                        ],
                      );
                    },
                  ),
                  const SizedBox(height: 16),
                  LayoutBuilder(
                    builder: (context, constraints) {
                      if (constraints.maxWidth > 600) {
                        return Row(
                          children: const [
                            Expanded(
                              child: _QuickTip(
                                icon: Icons.help_outline,
                                iconColor: AppTheme.green,
                                iconBgColor: AppTheme.greenLight,
                                title: 'Set reminders immediately',
                                subtitle:
                                    'Create follow-up reminders right after encounters',
                              ),
                            ),
                            SizedBox(width: 24),
                            Expanded(
                              child: _QuickTip(
                                icon: Icons.help_outline,
                                iconColor: AppTheme.amber,
                                iconBgColor: AppTheme.amberLight,
                                title: 'Complete all vitals',
                                subtitle:
                                    'Recording all vital signs reduces AI suggestions',
                              ),
                            ),
                          ],
                        );
                      }
                      return Column(
                        children: const [
                          _QuickTip(
                            icon: Icons.help_outline,
                            iconColor: AppTheme.green,
                            iconBgColor: AppTheme.greenLight,
                            title: 'Set reminders immediately',
                            subtitle:
                                'Create follow-up reminders right after encounters',
                          ),
                          SizedBox(height: 16),
                          _QuickTip(
                            icon: Icons.help_outline,
                            iconColor: AppTheme.amber,
                            iconBgColor: AppTheme.amberLight,
                            title: 'Complete all vitals',
                            subtitle:
                                'Recording all vital signs reduces AI suggestions',
                          ),
                        ],
                      );
                    },
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// Help card widget
class _HelpCard extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final Color iconBgColor;
  final String title;
  final String subtitle;

  const _HelpCard({
    required this.icon,
    required this.iconColor,
    required this.iconBgColor,
    required this.title,
    required this.subtitle,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      child: InkWell(
        onTap: () {},
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Container(
                width: 48,
                height: 48,
                decoration: BoxDecoration(
                  color: iconBgColor,
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Icon(icon, color: iconColor, size: 24),
              ),
              const SizedBox(height: 16),
              Text(
                title,
                style: Theme.of(context).textTheme.titleSmall,
              ),
              const SizedBox(height: 4),
              Text(
                subtitle,
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: AppTheme.textSecondary,
                    ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// FAQ item widget
class _FaqItem extends StatefulWidget {
  final String question;
  final String answer;

  const _FaqItem({
    required this.question,
    required this.answer,
  });

  @override
  State<_FaqItem> createState() => _FaqItemState();
}

class _FaqItemState extends State<_FaqItem> {
  bool _isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        InkWell(
          onTap: () => setState(() => _isExpanded = !_isExpanded),
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 12),
            child: Row(
              children: [
                Expanded(
                  child: Text(
                    widget.question,
                    style: Theme.of(context).textTheme.titleSmall,
                  ),
                ),
                Icon(
                  _isExpanded ? Icons.expand_less : Icons.expand_more,
                  color: AppTheme.textSecondary,
                ),
              ],
            ),
          ),
        ),
        if (_isExpanded)
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: Text(
              widget.answer,
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: AppTheme.textSecondary,
                  ),
            ),
          ),
      ],
    );
  }
}

/// Quick tip widget
class _QuickTip extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final Color iconBgColor;
  final String title;
  final String subtitle;

  const _QuickTip({
    required this.icon,
    required this.iconColor,
    required this.iconBgColor,
    required this.title,
    required this.subtitle,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: 32,
          height: 32,
          decoration: BoxDecoration(
            color: iconBgColor,
            borderRadius: BorderRadius.circular(16),
          ),
          child: Icon(icon, color: iconColor, size: 16),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: Theme.of(context).textTheme.titleSmall,
              ),
              const SizedBox(height: 4),
              Text(
                subtitle,
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                      color: AppTheme.textSecondary,
                    ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
